# action.yml
name: "Ingestinator"
description: "Generate LSTs in style"
inputs:
  java-version:
    description: "What version of Java does the project use? 8, 11, 17"
    required: true
    default: "8"
  build-tool:
    description: "Maven or Gradle"
    required: true
    default: "maven"
  build-tool-version:
    description: "Specify what a specific version of Maven or Gradle"
    required: false
  style:
    description: "Style format of your project"
    required: false
  repository-type:
    description: "Nexus or Artifactory?"
    required: true
    default: "nexus"
  repository-url:
    description: "Location of your artifact repository"
    required: true
  repository-username:
    description: "Username with write/publish permissions to the artifact repository"
    required: true
  repository-password:
    description: "Password for artifact repository account"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.java-version }}
    - ${{ inputs.build-tool }}
    - ${{ inputs.build-tool-version }}
    - ${{ inputs.style }}
    - ${{ inputs.repository-type }}
    - ${{ inputs.repository-url }}
    - ${{ inputs.repository-username }}
    - ${{ inputs.repository-password }}
